Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:00:01.916068
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:00:00.980684
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
The file does not exist
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:09.396607
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:00:00.977319
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
The file does not exist
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:22.714367
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:30.480146
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
Traceback (most recent call last):
  File "/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DU/du_batch.py", line 37, in <module>
    if  sys.argv[1] != '':
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DU/du_batch.py", line 121, in <module>
    result = run(command, stdout=PIPE, stderr=PIPE, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DU/f_intent_account_agg_to_surge_json_1.0/f_intent_account_agg_to_surge_json/f_intent_account_agg_to_surge_json_run.bat'
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:24.820266
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:11.240204
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:00:00.957353
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
The file does not exist
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59

 f_intent_account_agg_to_surge_json_1.0 started
0:01:23.835961
Following exception path
/home/ubuntu/appdata/Bombora_Renewal_PROD/BatchFile/DA_DBT/pythian.json
-1
59
{'tenant_id': 'bombora', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'bombora_dwh'}
{'tenant_id': 'pythian', 'db_driver': 'postgresql', 'db_password': 'Fcst1234$', 'db_host': 'ai-prod.cbtaanq5yhb4.us-east-1.rds.amazonaws.com', 'db_port': '5432', 'db_username': 'postgres', 'db_database': 'bombora_renewal_prod', 'db_schema': 'pythian_dwh', 'account_surge': 'y', 'lead': 'n', 'org': 'AI/PythianProd_Org_Intent'}
